sonata_admin:
    title: 'CarGuru Admin'
    security:
        handler: sonata.admin.security.handler.role
        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
#        user_block: '@SonataAdmin/Core/user_block.html.twig'
        add_block: '/admin/logout.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
